# Generated by Django 4.0.6 on 2022-08-10 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stripe_payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stripe_wallet', to=settings.AUTH_USER_MODEL, verbose_name='Wallet')),
            ],
        ),
        migrations.AlterField(
            model_name='transaction',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stripe_transactions', to='stripe_payment.stripewallet', verbose_name='Wallet'),
        ),
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
