# Generated by Django 4.0.6 on 2022-07-25 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scooter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_login', models.DateTimeField(auto_now_add=True)),
                ('updated_login', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=127, verbose_name='Название самоката')),
                ('price', models.IntegerField(default=0, verbose_name='Цена за самокат')),
                ('battery', models.IntegerField(default=0, verbose_name='Батарейка самоката')),
                ('mileage', models.IntegerField(default=0, verbose_name='Километраж самоката')),
                ('image', models.ImageField(upload_to='./scooters', verbose_name='Картинка самокатов')),
                ('code', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Номер самоката')),
                ('address', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Адрес самоката')),
                ('qr_code', models.ImageField(upload_to='./qr_codes', verbose_name='Qr code самоката')),
            ],
            options={
                'verbose_name': 'Scooter',
                'verbose_name_plural': 'Scooters',
                'db_table': 'scooters',
            },
        ),
    ]
