# Generated by Django 4.0.6 on 2022-07-28 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scooter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scooter',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес самоката'),
        ),
    ]
