# Generated by Django 4.0.6 on 2022-07-29 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scooter', '0003_scooter_address_en_scooter_address_kg_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scooter',
            name='address_kg',
        ),
        migrations.RemoveField(
            model_name='scooter',
            name='title_kg',
        ),
    ]
