# Generated by Django 4.0.6 on 2022-07-29 21:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scooter', '0004_remove_scooter_address_kg_remove_scooter_title_kg'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingScooterRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_login', models.DateTimeField(auto_now_add=True)),
                ('updated_login', models.DateTimeField(auto_now=True)),
                ('rate', models.PositiveSmallIntegerField(choices=[(1, 'Ok'), (2, 'Fine'), (3, 'Good'), (4, 'Amazing'), (5, 'Incredible')], null=True)),
                ('scooter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rating_scooters', to='scooter.scooter', verbose_name='Самокат')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rating_users_2', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Rating_scooter',
                'verbose_name_plural': 'Rating_scooters',
                'db_table': 'rating_scooters',
            },
        ),
    ]
