# Generated by Django 4.0.6 on 2022-08-05 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scooter', '0005_ratingscooterrelation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingscooterrelation',
            name='scooter',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rating_scooters', to='scooter.scooter', verbose_name='Самокат'),
        ),
        migrations.AlterField(
            model_name='ratingscooterrelation',
            name='user',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rating_users_2', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='scooter',
            name='code',
            field=models.CharField(blank=True, default='1HHN89FD', max_length=255, unique=True, verbose_name='Номер самоката'),
        ),
    ]
