# Generated by Django 4.0.6 on 2022-08-08 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scooter', '0006_alter_ratingscooterrelation_scooter_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ratingscooterrelation',
            old_name='first_login',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='ratingscooterrelation',
            old_name='updated_login',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='scooter',
            old_name='first_login',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='scooter',
            old_name='updated_login',
            new_name='updated_at',
        ),
    ]
