# Generated by Django 4.0.6 on 2022-08-10 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scooter', '0007_rename_first_login_ratingscooterrelation_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scooter',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
