# Generated by Django 4.0.6 on 2022-07-26 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default=996707000555, max_length=127, verbose_name='Номер телефона'),
            preserve_default=False,
        ),
    ]
