# Generated by Django 4.0.6 on 2022-07-22 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_social_network'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verifed',
            field=models.BooleanField(default=False, verbose_name='Прошел верикацию'),
        ),
    ]
