# Generated by Django 4.0.6 on 2022-07-22 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_is_verifed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.PositiveBigIntegerField(default='+996000000000', unique=True, verbose_name='Номер телефона'),
        ),
    ]
