# Generated by Django 4.0.6 on 2022-07-22 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.PositiveBigIntegerField(default='+996000000000', verbose_name='Номер телефона'),
        ),
    ]
