# Generated by Django 4.0.6 on 2022-07-29 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_user_is_verifed_remove_user_otp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_en',
            field=models.EmailField(max_length=254, null=True, unique=True, verbose_name='Электронная почта'),
        ),
        migrations.AddField(
            model_name='user',
            name='email_kg',
            field=models.EmailField(max_length=254, null=True, unique=True, verbose_name='Электронная почта'),
        ),
        migrations.AddField(
            model_name='user',
            name='email_ru',
            field=models.EmailField(max_length=254, null=True, unique=True, verbose_name='Электронная почта'),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name_en',
            field=models.CharField(max_length=125, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name_kg',
            field=models.CharField(max_length=125, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name_ru',
            field=models.CharField(max_length=125, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name_en',
            field=models.CharField(max_length=125, null=True, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name_kg',
            field=models.CharField(max_length=125, null=True, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name_ru',
            field=models.CharField(max_length=125, null=True, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='user',
            name='social_network_en',
            field=models.URLField(blank=True, default='email', null=True, verbose_name='Социальная сеть'),
        ),
        migrations.AddField(
            model_name='user',
            name='social_network_kg',
            field=models.URLField(blank=True, default='email', null=True, verbose_name='Социальная сеть'),
        ),
        migrations.AddField(
            model_name='user',
            name='social_network_ru',
            field=models.URLField(blank=True, default='email', null=True, verbose_name='Социальная сеть'),
        ),
    ]
