# Generated by Django 4.0.6 on 2022-07-29 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_email_en_user_email_kg_user_email_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_kg',
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name_kg',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name_kg',
        ),
        migrations.RemoveField(
            model_name='user',
            name='social_network_kg',
        ),
    ]
