# Generated by Django 4.0.6 on 2022-08-02 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_user_email_kg_remove_user_first_name_kg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=127, unique=True, verbose_name='Номер телефона'),
        ),
    ]
