# Generated by Django 4.0.6 on 2022-08-05 16:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_remove_user_email_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_code',
            field=models.CharField(blank=True, help_text='Для отправки кода через емайл', max_length=58),
        ),
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.PositiveIntegerField(default=0, help_text='Баланс пользователя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_code',
            field=models.CharField(help_text='Для отправки кода', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_code_expiry',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Срок годность кода'),
        ),
    ]
