# Generated by Django 4.0.6 on 2022-08-09 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_user_activation_code_alter_user_balance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='balance',
        ),
    ]
