# Generated by Django 4.0.6 on 2022-08-10 12:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_user_activation_code_alter_user_otp_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_code',
            field=models.CharField(blank=True, max_length=58, verbose_name='Код для верификации по емайлу'),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_code',
            field=models.CharField(max_length=30, null=True, verbose_name='Код верификации по номеру телефона'),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_code_expiry',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Срок годности кода'),
        ),
    ]
