version: "3.9"

services:
  db:
    image: postgres:14.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - my-network
    env_file:
      - .env


  scooter_kg_web:
    container_name: scooter_kg_cont
    build:
      context: .
    restart: unless-stopped
    volumes:
      - .:/app
    entrypoint: ./wsgi-entrypoint.sh
    depends_on:
      - db
      - redis
      - rabbitmq
    ports:
      - 8000:8000
    networks:
      - my-network
    env_file:
      - .env

  rabbitmq:
    image: rabbitmq:3.7.4
    container_name: rabbitmq
    env_file: .env
    networks:
      - my-network

  redis:
    container_name: send_mail_redis
    image: redis
    env_file:
      - .env
    networks:
      - my-network

  celery_worker:
    restart: always
    build:
      context: .
    image: django_celery_example_celery_worker
    volumes:
      - .:/app
    entrypoint: ./run-celery.sh
    env_file:
      - .env
    networks:
      - my-network
    depends_on:
      - redis
      - rabbitmq
      - scooter_kg_web

  celery_beat:
    build:
      context: .
    image: django_celery_example_celery_beat
    volumes:
      - .:/app
    entrypoint: ./run-celery_beat.sh
    env_file:
      - .env
    networks:
      - my-network
    depends_on:
      - redis
      - rabbitmq
      - scooter_kg_web


volumes:
  media:
  static:
  postgres_data:

networks:
  my-network:
