# Generated by Django 4.0.6 on 2022-07-28 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bicycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_login', models.DateTimeField(auto_now_add=True)),
                ('updated_login', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=127, verbose_name='Название велосипеда')),
                ('price', models.IntegerField(default=0, verbose_name='Цена за велосипеда')),
                ('image', models.ImageField(upload_to='./scooters', verbose_name='Картинка велосипедов')),
                ('code', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Номер велосипеда')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес самоката')),
                ('qr_code', models.ImageField(upload_to='./qr_codes', verbose_name='Qr code самоката')),
            ],
            options={
                'verbose_name': 'Bicycle',
                'verbose_name_plural': 'Bicycles',
                'db_table': 'bicycles',
            },
        ),
    ]
