# Generated by Django 4.0.6 on 2022-07-29 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bicycle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bicycle',
            name='address_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес самоката'),
        ),
        migrations.AddField(
            model_name='bicycle',
            name='address_kg',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес самоката'),
        ),
        migrations.AddField(
            model_name='bicycle',
            name='address_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес самоката'),
        ),
        migrations.AddField(
            model_name='bicycle',
            name='title_en',
            field=models.CharField(max_length=127, null=True, verbose_name='Название велосипеда'),
        ),
        migrations.AddField(
            model_name='bicycle',
            name='title_kg',
            field=models.CharField(max_length=127, null=True, verbose_name='Название велосипеда'),
        ),
        migrations.AddField(
            model_name='bicycle',
            name='title_ru',
            field=models.CharField(max_length=127, null=True, verbose_name='Название велосипеда'),
        ),
    ]
