# Generated by Django 4.0.6 on 2022-07-29 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bicycle', '0002_bicycle_address_en_bicycle_address_kg_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bicycle',
            name='address_kg',
        ),
        migrations.RemoveField(
            model_name='bicycle',
            name='title_kg',
        ),
    ]
