# Generated by Django 4.0.6 on 2022-08-05 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bicycle', '0004_ratingbicyclerelation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bicycle',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='КОд'),
        ),
        migrations.AlterField(
            model_name='bicycle',
            name='image',
            field=models.ImageField(upload_to='./scooters', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='bicycle',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='bicycle',
            name='title',
            field=models.CharField(max_length=127, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='bicycle',
            name='title_en',
            field=models.CharField(max_length=127, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='bicycle',
            name='title_ru',
            field=models.CharField(max_length=127, null=True, verbose_name='Название'),
        ),
    ]
