# Generated by Django 4.0.6 on 2022-08-08 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bicycle', '0006_alter_bicycle_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bicycle',
            old_name='first_login',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='bicycle',
            old_name='updated_login',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='ratingbicyclerelation',
            old_name='first_login',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='ratingbicyclerelation',
            old_name='updated_login',
            new_name='updated_at',
        ),
    ]
