# Generated by Django 4.0.6 on 2022-08-10 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(blank=True, db_index=True, max_length=128, unique=True, verbose_name='Номер заказа')),
                ('currency', models.CharField(default='KG', max_length=12, verbose_name='Валюта')),
                ('total_prices', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Общий цены заказа')),
                ('status', models.CharField(choices=[('инициированный', 'инициированный'), ('подтвержденный', 'потвержденный'), ('отправленный', 'отправленный'), ('доставлен', 'доставлен'), ('отменен', 'отменен')], default='инициированный', max_length=100)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='cart.cart')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_number', models.CharField(max_length=255, verbose_name='Номер телефона')),
                ('notes', models.TextField(blank=True, help_text='Расскажите нам все, что мы должны знать при доставке вашего заказа.')),
                ('address', models.CharField(max_length=127, verbose_name='Адрес доставки')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(blank=True, db_index=True, max_length=128, unique=True, verbose_name='Номер заказа продукта')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='KG', max_length=12)),
                ('payment_intent_id', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('status', models.CharField(choices=[('инициированный', 'инициированный'), ('подтвержденный', 'потвержденный'), ('отправленный', 'отправленный'), ('доставлен', 'доставлен'), ('отменен', 'отменен')], default='инициированный', max_length=100)),
                ('cart_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.cartitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='order.order')),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.shippingaddress'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
