# Generated by Django 4.0.6 on 2022-08-02 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paybox_payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='scooter',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
