# Generated by Django 4.0.6 on 2022-08-02 15:10

import datetime
from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bicycle', '0004_ratingbicyclerelation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scooter', '0005_ratingscooterrelation'),
        ('paybox_payments', '0002_remove_orderitem_order_remove_orderitem_scooter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Цена')),
                ('discount', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Скидка (%)')),
                ('month_duration', models.PositiveSmallIntegerField(verbose_name='Период (в месяцах)')),
                ('default', models.BooleanField(default=False, verbose_name='Пакет по умолчанию')),
            ],
            options={
                'verbose_name': 'Тарифный пакет',
                'verbose_name_plural': 'Тарифные пакеты',
            },
        ),
        migrations.CreateModel(
            name='ScooterTariffPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.DateField(default=datetime.time, verbose_name='Срок действия до')),
                ('bicycle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bycicle_tariffs', to='bicycle.bicycle')),
                ('package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations', to='paybox_payments.package')),
                ('scooter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tariffs', to='scooter.scooter')),
            ],
            options={
                'verbose_name': 'Тариф организации',
                'verbose_name_plural': 'Тарифы организаций',
            },
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Цена за 1 месяц')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
            },
        ),
        migrations.CreateModel(
            name='SitePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Сумма платежа')),
                ('bank_card_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер банковского счета')),
                ('success_transaction_description', models.TextField(blank=True, null=True, verbose_name='Описание при успешной транзакции')),
                ('failure_transaction_description', models.TextField(blank=True, null=True, verbose_name='Описание при неудачной транзакции')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Оплачен?')),
                ('is_applied2site', models.BooleanField(default=False, help_text='Если запрос на продление аренда сайта выполнился успешно, меняется на True', verbose_name='Применен ли для сайта?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('payed_at', models.DateTimeField(null=True, verbose_name='Дата и время оплаты')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
                ('tariff', models.ForeignKey(help_text='создайте новое отношение Сайт-Тариф: кнопка плюса', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='paybox_payments.scootertariffpackage', verbose_name='Сайт-Тариф')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
            },
        ),
        migrations.AddField(
            model_name='package',
            name='tariff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packages', to='paybox_payments.tariff'),
        ),
    ]
