# Generated by Django 4.0.6 on 2022-08-10 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MobileDevice',
        ),
    ]
