# Generated by Django 4.0.6 on 2022-08-11 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('method', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='EUR', max_length=12)),
                ('status', models.CharField(choices=[('open', 'open'), ('done', 'done')], default='open', max_length=100)),
                ('order_number', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='order.order', to_field='number')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
