# Generated by Django 4.0.6 on 2022-08-10 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('paybox_wallets', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayboxWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paybox_wallet', to=settings.AUTH_USER_MODEL, verbose_name='paybox_wallet')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=128)),
                ('type', models.CharField(choices=[('платеж получен', 'платеж получен'), ('платеж сделан', 'платеж сделан'), ('платеж снят', 'платеж снят'), ('платеж заполнен', 'платеж заполнен')], default='payment_made', max_length=64)),
                ('date', models.DateField(auto_now_add=True, verbose_name='Dates')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paybox_transactions', to='paybox_wallets.payboxwallet', verbose_name='paybox_wallet')),
            ],
        ),
        migrations.RemoveField(
            model_name='scootertariffpackage',
            name='bicycle',
        ),
        migrations.RemoveField(
            model_name='scootertariffpackage',
            name='package',
        ),
        migrations.RemoveField(
            model_name='scootertariffpackage',
            name='scooter',
        ),
        migrations.RemoveField(
            model_name='sitepayment',
            name='client',
        ),
        migrations.RemoveField(
            model_name='sitepayment',
            name='tariff',
        ),
        migrations.DeleteModel(
            name='Package',
        ),
        migrations.DeleteModel(
            name='ScooterTariffPackage',
        ),
        migrations.DeleteModel(
            name='SitePayment',
        ),
        migrations.DeleteModel(
            name='Tariff',
        ),
    ]
